openapi: 3.1.0
info:
  title: E-Commerce - Shipping Service
  description: |
    This API allows writing down marks on a Tic Tac Toe board
    and requesting the state of the board or of individual squares.
  version: 1.0.0
paths:

